spring:
  application:
    name: EtlEngine
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=SUPPORT;encrypt=true;trustServerCertificate=true;
    username: sa
    password: verYs3cret
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 300000     # 5 минут
      idle-timeout: 600000           # 10 минут
      max-lifetime: 1800000          # 30 минут
      connection-test-query: SELECT 1
  main:
    banner-mode: off
  sql.init:
    mode: always
    platform: sqlserver
kafka:
  bootstrap-servers: localhost:29092,localhost:39092,localhost:49092
  schema-registry-url: http://localhost:8081
logging:
  level:
    root: INFO
    org.apache.kafka: WARN
    org.apache.kafka.clients.consumer: WARN
    org.apache.kafka.common.utils.AppInfoParser: ERROR
    io.confluent.kafka.serializers: WARN
    io.confluent.kafka.serializers.KafkaAvroDeserializerConfig: WARN
