{
  "type": "record",
  "name": "TypeConversionDateTest",
  "namespace": "ru.pospelov.etl.avro",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "date_epoch",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "date_min",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "date_max",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "date_regular",
      "type": {
        "type": "int",
        "logicalType": "date"
      }
    },
    {
      "name": "date_null",
      "type": [
        "null",
        {
          "type": "int",
          "logicalType": "date"
        }
      ],
      "default": null
    }
  ]
}
