{
  "type": "record",
  "name": "TypeConversionTimeTest",
  "namespace": "ru.pospelov.etl.avro",
  "fields": [
    {
      "name": "id",
      "type": "int"
    },
    {
      "name": "time_val",
      "type": {
        "type": "long",
        "logicalType": "time-micros"
      }
    },
    {
      "name": "datetime_val",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "datetime2_val",
      "type": {
        "type": "long",
        "logicalType": "timestamp-micros"
      }
    },
    {
      "name": "smalldatetime_val",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "datetimeoffset_val",
      "type": "string"
    },
    {
      "name": "time_null",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "time-micros"
        }
      ],
      "default": null
    }
  ]
}
